import React from 'react';

export const audioquestionsByPage = {
  page1: [
    "A cozy cabin in a snowy forest.",
    "A futuristic cityscape at night.",
    "A peaceful beach with palm trees and a sunset.",
    "A mystical forest with glowing mushrooms.",
    "An ancient castle on a hilltop.",
    "A bustling market in a foreign city.",
    "A magical waterfall hidden in a lush jungle.",
    "A serene lake surrounded by mountains.",
    "A group of adventurers exploring a cave.",
    "A charming cafe on a cobblestone street.",
    "A colorful hot air balloon festival.",
    "A tranquil garden with blooming flowers.",
    "A majestic dragon flying over a medieval village.",
    "A vibrant street art mural in a urban alleyway.",
    "A mysterious island shrouded in mist.",
    "A dramatic thunderstorm over rolling hills.",
    "A whimsical fairy tale cottage in the woods.",
    "A breathtaking view from a mountaintop.",
    "An underwater city inhabited by mermaids.",
    "A magical library filled with ancient books.",
    "A charming old bookstore in a small town.",
  "A family of deer grazing in a meadow.",
  "A secret garden hidden behind a stone wall.",
  "A bustling street market in Marrakech.",
  "A whimsical carousel in a city park.",
  "A serene river winding through a forest.",
  "A cozy fireplace in a rustic cabin.",
  "A group of friends stargazing on a clear night.",
  "A colorful parade celebrating a cultural festival.",
  "A spooky haunted house on a hill.",
  "A quaint village nestled in the mountains.",
  "A peaceful countryside landscape with windmills.",
  "A majestic waterfall cascading into a pool.",
  "A lively street party with music and dancing.",
  "A tranquil meditation garden with a koi pond.",
  "A dramatic cliff overlooking the ocean.",
  "A magical forest with talking animals.",
  "A futuristic space station orbiting a planet.",
  "A vintage train traveling through scenic countryside.",
  "A picturesque vineyard in Tuscany.",
  "A whimsical fairytale castle in the clouds.",
  "A bustling harbor with sailboats and seagulls.",
  "A cozy cafe on a rainy day.",
  "A group of children playing in a field of flowers.",
  "A majestic eagle soaring through the sky.",
  "A hidden cave with glowing crystals.",
  "A charming street in a historic European city.",
  "A peaceful Japanese garden with cherry blossoms.",
  "A magical portal in the middle of a forest.",
  "A colorful coral reef teeming with marine life.",
  "A mysterious abandoned mansion in the woods.",
  ],
  page2: [
    "A mysterious abandoned mansion in the woods.",
  "A traditional Japanese tea ceremony.",
  "A picturesque lighthouse overlooking the sea.",
  "A vibrant market square in Morocco.",
  "A tranquil lake surrounded by autumn trees.",
  "A futuristic city skyline with flying cars.",
  "A cozy reading nook by a window.",
  "A group of adventurers exploring a lost city.",
  "A serene mountain lake reflecting the sunrise.",
  "A whimsical ice cream shop with unique flavors.",
  "A majestic waterfall hidden in a lush jungle.",
  "A quaint cottage covered in ivy.",
  "A bustling night market with street food vendors.",
  "A peaceful village in the countryside.",
  "A colorful hot air balloon festival.",
  "A magical forest with glowing fireflies.",
  "A charming cafe on a cobblestone street.",
  "A tranquil garden with blooming flowers.",
  "A majestic dragon flying over a medieval village.",
  "A vibrant street art mural in an urban alleyway.",
  "A mysterious island shrouded in mist.",
  "A dramatic thunderstorm over rolling hills.",
  "A whimsical fairy tale cottage in the woods.",
  "A breathtaking view from a mountaintop.",
  "An underwater city inhabited by mermaids.",
  "A magical library filled with ancient books.",
  "A charming old bookstore in a small town.",
  "A family of deer grazing in a meadow.",
  "A secret garden hidden behind a stone wall.",
  "A bustling street market in Marrakech.",
  "A whimsical carousel in a city park.",
  "A serene river winding through a forest.",
  "A cozy fireplace in a rustic cabin.",
  "A group of friends stargazing on a clear night.",
  "A colorful parade celebrating a cultural festival.",
  "A spooky haunted house on a hill.",
  "A quaint village nestled in the mountains.",
  "A peaceful countryside landscape with windmills.",
  "A majestic waterfall cascading into a pool.",
  "A lively street party with music and dancing.",
  "A tranquil meditation garden with a koi pond.",
  "A dramatic cliff overlooking the ocean.",
  "A magical forest with talking animals.",
  "A futuristic space station orbiting a planet.",
  "A vintage train traveling through scenic countryside.",
  "A picturesque vineyard in Tuscany.",
  "A whimsical fairytale castle in the clouds.",
  "A bustling harbor with sailboats and seagulls.",
  "A cozy cafe on a rainy day.",
  "A group of children playing in a field of flowers.",
  "A majestic eagle soaring through the sky.",
  "A hidden cave with glowing crystals.",
  "A charming street in a historic European city.",
  "A peaceful Japanese garden with cherry blossoms.",
  "A magical portal in the middle of a forest.",
  "A colorful coral reef teeming with marine life.",
  "A mysterious abandoned mansion in the woods.",
  "A traditional Japanese tea ceremony.",
  "A picturesque lighthouse overlooking the sea.",
  "A vibrant market square in Morocco.",
  "A tranquil lake surrounded by autumn trees.",
  "A futuristic city skyline with flying cars.",
  "A cozy reading nook by a window.",
  "A group of adventurers exploring a lost city.",
  "A serene mountain lake reflecting the sunrise.",
  "A whimsical ice cream shop with unique flavors.",
  "A majestic waterfall hidden in a lush jungle.",
  "A quaint cottage covered in ivy.",
  "A bustling night market with street food vendors.",
  "A peaceful village in the countryside.",
  "A colorful hot air balloon festival.",
  "A magical forest with glowing fireflies.",
  "A charming cafe on a cobblestone street.",
  "A tranquil garden with blooming flowers.",
  "A majestic dragon flying over a medieval village.",
  "A vibrant street art mural in an urban alleyway.",
  "A mysterious island shrouded in mist.",
  "A dramatic thunderstorm over rolling hills.",
  "A whimsical fairy tale cottage in the woods.",
  "A breathtaking view from a mountaintop.",
  "An underwater city inhabited by mermaids.",
  "A magical library filled with ancient books.",
  "A charming old bookstore in a small town.",
  "A family of deer grazing in a meadow.",
  "A secret garden hidden behind a stone wall.",
  "A bustling street market in Marrakech.",
  "A whimsical carousel in a city park.",
  "A serene river winding through a forest.",
  "A cozy fireplace in a rustic cabin.",
  "A group of friends stargazing on a clear night.",
  "A colorful parade celebrating a cultural festival.",
  "A spooky haunted house on a hill.",
  "A quaint village nestled in the mountains.",
  "A peaceful countryside landscape with windmills.",
  "A majestic waterfall cascading into a pool.",
  "A lively street party with music and dancing.",
  "A tranquil meditation garden with a koi pond.",
  "A dramatic cliff overlooking the ocean.",
  "A magical forest with talking animals.",
  "A futuristic space station orbiting a planet.",
  "A vintage train traveling through scenic countryside.",
  "A picturesque vineyard in Tuscany.",
  "A whimsical fairytale castle in the clouds.",
  "A bustling harbor with sailboats and seagulls.",
  "A cozy cafe on a rainy day.",
  "A group of children playing in a field of flowers.",
  "A majestic eagle soaring through the sky.",
  "A hidden cave with glowing crystals.",
  "A charming street in a historic European city.",
  "A peaceful Japanese garden with cherry blossoms.",
  "A magical portal in the middle of a forest.",
  "A colorful coral reef teeming with marine life.",
  "A mysterious abandoned mansion in the woods.",
  "A traditional Japanese tea ceremony.",
  "A picturesque lighthouse overlooking the sea.",
  "A vibrant market square in Morocco.",
  "A tranquil lake surrounded by autumn trees.",
  "A futuristic city skyline with flying cars.",
  "A cozy reading nook by a window.",
  "A group of adventurers exploring a lost city.",
  "A serene mountain lake reflecting the sunrise.",
  "A whimsical ice cream shop with unique flavors.",
  "A majestic waterfall hidden in a lush jungle.",
  "A quaint cottage covered in ivy.",
  "A bustling night market with street food vendors.",
  "A peaceful village in the countryside.",
  "A colorful hot air balloon festival.",
  "A magical forest with glowing fireflies.",
  "A charming cafe on a cobblestone street.",
  ]
  // Add more pages as needed
};
