import React from "react";

export const imagequestionsByPage = {
  page1: [
    "Welcome to our virtual event, 'Hello, how are you?' 'You're amazing!'",
    "Hello, 'Welcome to our online conference.' 'How can we assist you?'",
    "Greetings, 'We're thrilled to have you at our webinar.' 'Ready to learn?'",
    "Welcome to our virtual workshop, 'We're excited to see you here!'",
    "Hello, 'Welcome to our online seminar.' 'What's on your mind?'",
    "Greetings, 'Thank you for joining our virtual panel discussion.'",
    "Greetings from our team, 'Thank you for joining us today.'",
    "Welcome to our webinar, 'We're excited to have you here!'",
    "Hello, 'Welcome to our online workshop.' 'How can we assist you?'",
    "Greetings, 'We're thrilled to see you at our conference.' 'Ready to learn?'",
    "Welcome to our live stream, 'Sit back, relax, and enjoy the show.'",
    "Hello there, 'Thanks for tuning in to our podcast.' 'Ready to dive in?'",
    "Greetings from our community, 'We're glad to have you with us.' 'Let's connect!'",
    "Welcome to our online class, 'Get ready to learn something new.'",
    "Hello, 'Welcome to our virtual book club.' 'What's on your reading list?'",
    "Greetings, 'Thank you for attending our virtual networking event.'",
    "Welcome to our online forum, 'Let's start a meaningful discussion.'",
    "Hello there, 'Welcome to our virtual support group.' 'We're here to help.'",
    "Greetings, 'Welcome to our online cooking class.' 'Let's get cooking!'",
    "Welcome to our webinar series, 'Get ready for an informative session.'",
    "Hello, 'Welcome to our virtual art exhibition.' 'Enjoy the creativity!'",
    "Greetings, 'Welcome to our online gaming community.' 'Let's play!'",
    "Welcome to our virtual concert, 'Get ready to groove to the music.'",
    "Hello there, 'Welcome to our virtual yoga session.' 'Let's find our zen.'",
    "Greetings from our team, 'Welcome to our virtual team building event.'",
    "Welcome to our online workshop, 'Get ready to unlock your creativity.'",
  ],
  page2: [
    "Greetings, 'Welcome to our virtual conference.' 'Ready to network?'",
    "Welcome to our webinar, 'Get ready for an insightful discussion.'",
    "Hello, 'Welcome to our virtual panel discussion.' 'Let's share ideas!'",
    "Greetings from our team, 'Welcome to our virtual workshop.' 'Let's get started!'",
    "Welcome to our online seminar, 'Prepare to gain new knowledge.'",
    "Hello, 'Welcome to our virtual training session.' 'Let's improve together.'",
    "Greetings, 'Welcome to our virtual lecture.' 'Get ready to learn.'",
    "Welcome to our webinar series, 'Prepare for an engaging conversation.'",
    "Hello there, 'Welcome to our virtual town hall meeting.' 'Let's discuss.'",
    "Greetings, 'Welcome to our online forum.' 'Join the conversation.'",
    "Welcome to our virtual summit, 'Get ready for a day of inspiration.'",
    "Hello, 'Welcome to our virtual trade show.' 'Explore our exhibits.'",
    "Greetings from our team, 'Welcome to our online job fair.' 'Good luck!'",
    "Welcome to our virtual expo, 'Prepare to discover new products.'",
    "Hello, 'Welcome to our virtual hackathon.' 'Let's innovate.'",
    "Greetings, 'Welcome to our online career fair.' 'Ready to connect?'",
    "Welcome to our virtual festival, 'Get ready to celebrate.'",
    "Hello there, 'Welcome to our virtual book festival.' 'Explore new reads.'",
    "Greetings, 'Welcome to our online concert.' 'Enjoy the music.'",
    "Welcome to our virtual art show, 'Prepare to be inspired.'",
    "Hello, 'Welcome to our virtual fashion show.' 'Check out the designs.'",
    "Greetings from our team, 'Welcome to our virtual film festival.' 'Enjoy the movies.'",
    "Welcome to our online theater, 'Get ready for a virtual performance.'",
    "Hello, 'Welcome to our virtual comedy show.' 'Prepare to laugh.'",
    "Greetings, 'Welcome to our online poetry reading.' 'Enjoy the verses.'",
    "Welcome to our virtual magic show, 'Prepare to be amazed.'",
    "Hello there, 'Welcome to our virtual dance performance.' 'Let's dance.'",
    "Greetings, 'Welcome to our online cooking competition.' 'Let's cook!'",
    "Welcome to our virtual gaming tournament, 'Get ready to play.'",
    "Hello, 'Welcome to our virtual chess match.' 'Ready to strategize?'",
    "Greetings from our team, 'Welcome to our online trivia night.' 'Let's quiz!'",
    "Welcome to our virtual escape room, 'Prepare to solve puzzles.'",
    "Hello, 'Welcome to our virtual treasure hunt.' 'Let's find the clues.'",
    "Greetings, 'Welcome to our online scavenger hunt.' 'Ready to search?'",
    "Welcome to our virtual team building activity, 'Prepare for teamwork.'",
    "Hello there, 'Welcome to our virtual icebreaker session.' 'Let's bond.'",
    "Greetings, 'Welcome to our online mindfulness session.' 'Find your calm.'",
    "Welcome to our virtual yoga class, 'Prepare to stretch and relax.'",
    "Hello, 'Welcome to our virtual meditation session.' 'Let's find peace.'",
    "Greetings from our team, 'Welcome to our online fitness class.' 'Let's work out.'",
    "Welcome to our virtual dance class, 'Prepare to move and groove.'",
    "Hello, 'Welcome to our virtual painting workshop.' 'Let's get creative.'",
  ],
  // Add more pages as needed
};
