import React from "react";

export const questionsByPage = {
  page1: [
    "Write a letter to your boss asking for a leave extension.",
    "Compose a poem to impress your crush.",
    "Draft an email to a client requesting a meeting.",
    "Create a short story about a detective solving a mystery.",
    "Write a persuasive essay on the importance of recycling.",
    "Write a letter to your future self.",
    "Create a recipe for a delicious homemade dessert.",
    "Draft a letter to a company requesting a donation for a charity event.",
    "Write a persuasive argument for why homework should be banned.",
    "Write a short story about a magical adventure.",
    "Create a list of tips for staying motivated at work.",
    "Draft a letter to a local politician about an environmental issue.",
    "Write a persuasive essay on the importance of mental health awareness.",
    "How can I start a regular meditation practice?",
    "What are some ways to boost my creativity?",
    "What are some benefits of regular physical activity?",
    "How do I make a budget-friendly grocery list?",
    "What are some effective ways to manage my time?",
    "What are some benefits of spending time outdoors?",
    "How can I improve my problem-solving skills?",
    "What are some easy ways to improve my mood?",
    "What are some benefits of learning to play an instrument?",
    "How do I create a productive workspace?",
    "What are some ways to improve my focus and concentration?",
    "What are some easy ways to be more eco-friendly?",
    "Craft a funny story about a mischievous pet.",
    "Write a poem about the changing seasons.",
    "Create a list of tips for starting a small business.",
    "Draft a letter to a company requesting a refund for a faulty product.",
    "Write a poem about the power of kindness.",
    "Compose a letter to your future self reflecting on your achievements.",
    "Craft a short story about a mysterious disappearance.",
    "Write a speech on the importance of mental health in the workplace.",
    "Create a list of tips for living a more sustainable lifestyle.",
    "Draft a letter to a family member you haven't spoken to in a while.",
    "Write a poem about the beauty of friendship.",
    "Compose a letter to your future self reflecting on your journey so far.",
    "Craft a short story about a mysterious disappearance.",
    "Create a list of tips for staying focused while studying.",
    "Draft a letter to a company requesting a job application.",
    "Write a persuasive argument for why everyone should learn a third language.",
    "Compose a letter to your future child sharing advice for navigating life's challenges.",
    "Craft a speech on the importance of kindness and compassion.",
    "Create a list of tips for maintaining a healthy work-life balance.",
    "Draft a letter to a local charity offering to volunteer your time.",
    "Write a poem about the beauty of friendship.",
    "Compose a letter to your future self reflecting on your achievements.",
    "Craft a short story about a group of friends on a road trip.",
    "Write a speech on the importance of voting in elections.",
    "Create a list of tips for staying positive during difficult times.",
    "Compose a letter to your future self reflecting on your achievements.",
    "Craft a short story about a group of friends on a road trip.",
    "Write a speech on the importance of voting in elections.",
    "Create a list of tips for staying positive during difficult times.",
    "Draft a letter to a local newspaper expressing your opinion on a current issue.",
    "Write a persuasive argument for why everyone should learn a second language.",
    "Compose a letter to your future child sharing your favorite childhood memories.",
    "Craft a short story about a group of adventurers exploring a lost city.",
    "Write a speech on the importance of mental health in the workplace.",
    "Create a list of tips for living a more sustainable lifestyle.",
    "Draft a letter to a family member you haven't spoken to in a while.",
    "Write a poem about the beauty of friendship.",
    "Compose a letter to your future self reflecting on your journey so far.",
    "Craft a short story about a mysterious disappearance.",
    "Create a list of tips for staying focused while studying.",
    "Draft a letter to a company requesting a job application.",
    "Write a persuasive argument for why everyone should learn a third language.",
    "Compose a letter to your future child sharing advice for navigating life's challenges.",
    "Craft a speech on the importance of kindness and compassion.",
    "Create a list of tips for maintaining a healthy work-life balance.",
    "Draft a letter to a local charity offering to volunteer your time.",
    "Write a poem about the beauty of friendship.",
    "Compose a letter to your future self reflecting on your achievements.",
    "Draft a letter to a family member you haven't spoken to in a while.",
    "Write a poem about the beauty of friendship.",
    "Compose a letter to your future self reflecting on your journey so far.",
    "Craft a short story about a mysterious disappearance.",
    "Create a list of tips for staying focused while studying.",
    "Draft a letter to a company requesting a job application.",
    "Write a persuasive argument for why everyone should learn a third language.",
    "Compose a letter to your future child sharing advice for navigating life's challenges.",
  ],
  // Add more pages as needed
};
